# Generated by Django 2.2.5 on 2019-09-28 22:38

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('blurb', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
            managers=[
                ('links', django.db.models.manager.Manager()),
            ],
        ),
    ]
