# Generated by Django 2.2.5 on 2019-09-29 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190928_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
